runtime: python27
api_version: 1
threadsafe: true
service: default

handlers:
- url: /
  static_files: dist/flickr-tag-search/index.html
  upload: dist/flickr-tag-search/index.html

- url: /
  static_dir: dist/flickr-tag-search