runtime: python37
service: default

handlers:
- url: /(.*\.[A-Za-z0-9]{1,4})$
  static_files: dist/flickr-tag-search/\1
  upload: dist/flickr-tag-search/(.*\.[A-Za-z0-9]{1,4})$

- url: /(.*)$
  static_files: dist/flickr-tag-search/index.html
  upload: dist/flickr-tag-search/index.html